version: '3.8'
services:
  firebird:
    image: firebirdsql/firebird:latest
    container_name: firebird
    restart: unless-stopped
    environment:
      - FIREBIRD_DATABASE=cafeteria.fdb
      - FIREBIRD_USER=SYSDBA
      - FIREBIRD_PASSWORD=masterkey
    ports:
      - "3051:3050"  # Puerto predeterminado de Firebird
    volumes:
      - ./cafeteria.fdb:/firebird/data/cafeteria.fdb  # Archivo de base de datos
      - ./cafeteria.sql:/docker-entrypoint-initdb.d/cafeteria.sql  # Script de inicialización
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 1G
