# #debes usar una variable de entorno para la direccion de la base de datos
# #lee la documentacion de la imagen calderonperaza/dbversusapp
# #esto es para produccion dockerizado
# #para correr ejecuta
# #docker-compose up -d
# version: '3.1'
# services:
#   appversus:
#     image: calderonperaza/dbversusapp:1.0
#     container_name: appversus
#     restart: unless-stopped    
#     ports:
#       - "3000:3000"
#     environment:
#       HOST_DB: mysql
#     deploy:
#           resources:
#             limits:
#               cpus: '1'
#               memory: 1G
#             reservations:
#               cpus: '1'
#               memory: 1G
# #SI LA BASE DE DATOS ES MYSQL
#   mysql:
#     image: mysql:8.0-debian
#     container_name: mysql
#     restart: unless-stopped
#     environment:
#       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"      
#       MYSQL_DATABASE: cafeteria      
#     ports:
#       - "3306:3306"
#     volumes:
#       - ../mysql/cafeteria.sql:/docker-entrypoint-initdb.d/cafeteria.sql
#     deploy:
#           resources:
#             limits:
#               cpus: '1'
#               memory: 1G
#             reservations:
#               cpus: '1'
#               memory: 1G




# version: '3.8'

services:
  # Servicio principal de la app Nuxt
  appversus:
    build:
      context: .
      dockerfile: Dockerfile
      # CAMBIAR A LA IMAGEN DE SU APP
    image: sams126/dbversusapp:1.0
    container_name: appversus
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      HOST_DB: rethinkdb  
    

  # Servicio de la base de datos RethinkDB
  rethinkdb:
    image: rethinkdb:latest
    container_name: rethinkdb_container
    command: rethinkdb --bind all
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 15s
      retries: 3
    volumes:
      - ../RethinkDB/script.js:/docker-entrypoint-initdb.d/init-rethinkdb.js:ro 

 
