#debes usar una variable de entorno para la direccion de la base de datos
#lee la documentacion de la imagen calderonperaza/dbversusapp
#esto es para produccion dockerizado
#para correr ejecuta
#docker-compose up -d
version: '3.1'
services:
  appversus:
    image: diegoosorio24/dbversusapp:1.1
    container_name: appversus
    restart: unless-stopped    
    ports:
      - "3000:3000"
    environment:
      - HOST_DB=oracle
    deploy:
          resources:
            limits:
              cpus: '1'
              memory: 1G
            reservations:
              cpus: '1'
              memory: 1G
#SI LA BASE DE DATOS ES MYSQL
  oracle:
    image: gvenzl/oracle-free:23.5-amd64
    container_name: oracle
    restart: unless-stopped
    environment:
      ORACLE_PASSWORD: "oracle"  # Contraseña de SYS y SYSTEM
    ports:
      - "1521:1521"  # Puerto de Oracle
    volumes:
      - ../oracle/cafeteria.sql:/docker-entrypoint-initdb.d/cafeteria.sql  # Importación del archivo SQL
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 1G    