
#debes usar una variable de entorno para la direccion de la base de datos
#lee la documentacion de la imagen calderonperaza/dbversusapp
#esto es para produccion dockerizado
#para correr ejecuta
#docker-compose up -d
version: '3.1'
services:
  appversus:
    image: calderonperaza/dbversusapp:1.0
    container_name: appversus
    restart: unless-stopped    
    ports:
      - "3000:3000"
    environment:
      - HOST_DB=mysql
    deploy:
          resources:
            limits:
              cpus: '1'
              memory: 1G
            reservations:
              cpus: '1'
              memory: 1G

# SI LA BASE ES MARIADB
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'    
      MMYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_DATABASE: 'cafeteria'     
    ports:
      - "3306:3306"
    volumes:
      - ../mariadb/cafeteria.sql:/docker-entrypoint-initdb.d/cafeteria.sql
    deploy:
          resources:
            limits:
              cpus: '1'
              memory: 1G
            reservations:
              cpus: '1'
              memory: 1G 