#Este es el docker compose para levantar un contenedor de mysql
#No hay ningun volumen porque la data es temporal, solo para las pruebas
# version de mysql 8.0-debian
# se usa sin password de root
#el esquema se importa del archivo cafeteria.sql
#el cual se copia en la carpeta /docker-entrypoint-initdb.d
services:
  mysql:
    image: mysql:8.0-debian
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"      
      MYSQL_DATABASE: restaurante      
    ports:
      - "3306:3306"
    volumes:
      - ./cafeteria.sql:/docker-entrypoint-initdb.d

    